"""Seed product catalog for Billy's Store."""
from datetime import datetime, timezone
import uuid


def _now():
    return datetime.now(timezone.utc).isoformat()


def _p(**kw):
    kw.setdefault("id", str(uuid.uuid4()))
    kw.setdefault("currency", "USD")
    kw.setdefault("created_at", _now())
    kw.setdefault("reviews", [])
    return kw


COLORS = {
    "black": {"name": "Noir", "hex": "#111111"},
    "white": {"name": "Blanc cassé", "hex": "#F5F1EA"},
    "beige": {"name": "Beige", "hex": "#D9C7A7"},
    "camel": {"name": "Camel", "hex": "#A87B4B"},
    "gold": {"name": "Doré", "hex": "#C5A880"},
    "silver": {"name": "Argenté", "hex": "#C7C7CB"},
    "navy": {"name": "Bleu nuit", "hex": "#1F2A44"},
    "sand": {"name": "Sable", "hex": "#E6D9C0"},
    "olive": {"name": "Olive", "hex": "#6B6F3E"},
    "rose": {"name": "Rose pâle", "hex": "#E7C9C0"},
    "ivory": {"name": "Ivoire", "hex": "#FBF6EC"},
    "charcoal": {"name": "Anthracite", "hex": "#2D2D2F"},
}

SIZES_APPAREL = ["XS", "S", "M", "L", "XL"]
SIZES_KIDS = ["2A", "4A", "6A", "8A", "10A"]
SIZES_RING = ["48", "50", "52", "54", "56"]
SIZES_BAG = ["Unique"]


SAMPLE_REVIEWS = [
    {"author": "Amélie D.", "rating": 5, "date": "2025-11-04", "title": "Qualité irréprochable",
     "body": "Coupe parfaite, finitions soignées. Je recommande vivement.", "photo": None},
    {"author": "Julien P.", "rating": 5, "date": "2025-10-22", "title": "Élégance discrète",
     "body": "Exactement ce que je cherchais. La matière est douce et résistante.", "photo": None},
    {"author": "Sarah M.", "rating": 4, "date": "2025-10-11", "title": "Très belle pièce",
     "body": "Livraison rapide, produit conforme aux photos. Je retire une étoile pour la boîte un peu simple.", "photo": None},
]


def _reviews(count):
    return SAMPLE_REVIEWS[: min(count, len(SAMPLE_REVIEWS))]


SEED_PRODUCTS = [
    # ============ JEWELRY (6) ============
    _p(
        name_fr="Bague Solitaire Aurore",
        name_en="Aurore Solitaire Ring",
        slug="aurore-solitaire-ring",
        category="jewelry",
        subcategory="Bagues",
        price=289.00,
        compare_at=340.00,
        images=[
            "https://images.unsplash.com/photo-1625516152414-8f33eef3d660?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1543295204-2ae345412549?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Solitaire délicat en or 18 carats serti d'une pierre taille brillant. Un bijou intemporel pensé pour être porté au quotidien ou pour les grandes occasions.",
        description_en="Delicate 18k gold solitaire set with a brilliant-cut stone. A timeless piece designed for daily wear or special moments.",
        composition_fr="Or 18 carats · Pierre naturelle 0.25ct",
        composition_en="18k gold · 0.25ct natural stone",
        variants={"sizes": SIZES_RING, "colors": [COLORS["gold"], COLORS["silver"]], "materials": ["Or", "Argent"]},
        rating=4.9, reviews_count=48, reviews=_reviews(3),
        badges=["bestseller"], stock=12,
    ),
    _p(
        name_fr="Boucles d'oreilles Céleste",
        name_en="Céleste Earrings",
        slug="celeste-earrings",
        category="jewelry",
        subcategory="Boucles d'oreilles",
        price=145.00,
        images=[
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Créoles épurées en argent massif plaqué or, un classique revisité avec une torsade subtile.",
        description_en="Refined hoop earrings in gold-plated sterling silver with a subtle twist detail.",
        composition_fr="Argent 925 · Plaqué or 3 microns",
        composition_en="Sterling silver 925 · 3-micron gold plating",
        variants={"sizes": SIZES_BAG, "colors": [COLORS["gold"], COLORS["silver"]], "materials": []},
        rating=4.7, reviews_count=32, reviews=_reviews(2),
        badges=["new"], stock=20,
    ),
    _p(
        name_fr="Collier Fil d'Or",
        name_en="Golden Thread Necklace",
        slug="golden-thread-necklace",
        category="jewelry",
        subcategory="Colliers",
        price=210.00,
        images=[
            "https://images.unsplash.com/photo-1611652022419-a9419f74343d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Chaîne fine en or jaune, longueur ajustable, un bijou signature qui se porte seul ou superposé.",
        description_en="Delicate yellow gold chain with adjustable length, meant to be worn solo or layered.",
        composition_fr="Or jaune 18 carats · 42-45cm ajustable",
        composition_en="18k yellow gold · 42-45cm adjustable",
        variants={"sizes": SIZES_BAG, "colors": [COLORS["gold"]], "materials": []},
        rating=4.8, reviews_count=27, reviews=_reviews(2),
        badges=[], stock=15,
    ),
    _p(
        name_fr="Bracelet Jonc Minimaliste",
        name_en="Minimalist Bangle",
        slug="minimalist-bangle",
        category="jewelry",
        subcategory="Bracelets",
        price=95.00,
        images=[
            "https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1602752250015-52934bc45613?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Un jonc rigide au design épuré, à porter seul ou en superposition avec vos pièces favorites.",
        description_en="A rigid bangle with a clean design — wear alone or stack with your favourite pieces.",
        composition_fr="Laiton plaqué or · Fermoir invisible",
        composition_en="Gold-plated brass · Hidden clasp",
        variants={"sizes": ["S", "M", "L"], "colors": [COLORS["gold"], COLORS["silver"]], "materials": []},
        rating=4.5, reviews_count=18, reviews=_reviews(1),
        badges=[], stock=0,
    ),
    _p(
        name_fr="Sac Enveloppe Cuir Nappa",
        name_en="Nappa Envelope Bag",
        slug="nappa-envelope-bag",
        category="jewelry",
        subcategory="Sacs",
        price=395.00,
        compare_at=460.00,
        images=[
            "https://images.unsplash.com/photo-1544816155-12df9643f363?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1591561954557-26941169b49e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Sac enveloppe en cuir Nappa italien, doublure suédine, format parfait pour le jour comme pour le soir.",
        description_en="Envelope clutch in Italian Nappa leather with suede lining — perfect for day or evening.",
        composition_fr="Cuir Nappa italien · Doublure suédine",
        composition_en="Italian Nappa leather · Suede lining",
        variants={"sizes": SIZES_BAG, "colors": [COLORS["black"], COLORS["camel"], COLORS["ivory"]], "materials": []},
        rating=4.9, reviews_count=41, reviews=_reviews(3),
        badges=["bestseller"], stock=8,
    ),
    _p(
        name_fr="Ceinture Cuir Fine",
        name_en="Slim Leather Belt",
        slug="slim-leather-belt",
        category="jewelry",
        subcategory="Ceintures",
        price=79.00,
        images=[
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1624222247344-550fb60583dc?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Ceinture fine en cuir pleine fleur, boucle en laiton brossé.",
        description_en="Slim full-grain leather belt with a brushed brass buckle.",
        composition_fr="Cuir pleine fleur · Boucle laiton",
        composition_en="Full-grain leather · Brass buckle",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["camel"]], "materials": []},
        rating=4.6, reviews_count=22, reviews=_reviews(2),
        badges=[], stock=30,
    ),

    # ============ WOMEN (7) ============
    _p(
        name_fr="Blazer Structuré Ambre",
        name_en="Ambre Structured Blazer",
        slug="ambre-structured-blazer",
        category="women",
        subcategory="Vestes",
        price=320.00,
        images=[
            "https://images.unsplash.com/photo-1613915617430-8ab0fd7c6baf?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Blazer double boutonnage en laine mélangée, coupe structurée et épaules marquées.",
        description_en="Double-breasted wool-blend blazer with structured cut and defined shoulders.",
        composition_fr="70% laine · 25% viscose · 5% élasthanne",
        composition_en="70% wool · 25% viscose · 5% elastane",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["charcoal"], COLORS["camel"]], "materials": []},
        rating=4.8, reviews_count=36, reviews=_reviews(3),
        badges=["bestseller"], stock=14,
    ),
    _p(
        name_fr="Robe Midi Écarlate",
        name_en="Scarlet Midi Dress",
        slug="scarlet-midi-dress",
        category="women",
        subcategory="Robes",
        price=245.00,
        images=[
            "https://images.unsplash.com/photo-1662532577856-e8ee8b138a8b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1595777457583-95e059d581b8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Robe midi en satin fluide, coupe cintrée, ceinture nouée à la taille.",
        description_en="Midi dress in fluid satin with fitted cut and tie waist detail.",
        composition_fr="100% satin de viscose",
        composition_en="100% viscose satin",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["ivory"]], "materials": []},
        rating=4.7, reviews_count=29, reviews=_reviews(2),
        badges=["new"], stock=10,
    ),
    _p(
        name_fr="Pull Cachemire Nuage",
        name_en="Nuage Cashmere Sweater",
        slug="nuage-cashmere-sweater",
        category="women",
        subcategory="Mailles",
        price=280.00,
        images=[
            "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Pull ample 100% cachemire, col rond, maille douce et enveloppante.",
        description_en="Relaxed 100% cashmere sweater with round neck and soft enveloping knit.",
        composition_fr="100% cachemire",
        composition_en="100% cashmere",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["ivory"], COLORS["sand"], COLORS["charcoal"], COLORS["rose"]], "materials": []},
        rating=4.9, reviews_count=52, reviews=_reviews(3),
        badges=["bestseller"], stock=18,
    ),
    _p(
        name_fr="Chemise Poplin Blanche",
        name_en="White Poplin Shirt",
        slug="white-poplin-shirt",
        category="women",
        subcategory="Chemises",
        price=125.00,
        images=[
            "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1564257577-8bda7d3d5b74?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Chemise oversize en popeline de coton, coupe droite, manches longues à poignets.",
        description_en="Oversize cotton poplin shirt with straight cut and cuffed sleeves.",
        composition_fr="100% coton poplin",
        composition_en="100% cotton poplin",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["ivory"], COLORS["navy"]], "materials": []},
        rating=4.6, reviews_count=24, reviews=_reviews(2),
        badges=[], stock=22,
    ),
    _p(
        name_fr="Pantalon Tailleur Fluide",
        name_en="Tailored Trousers",
        slug="tailored-trousers",
        category="women",
        subcategory="Pantalons",
        price=185.00,
        images=[
            "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1548624313-0396c75e4b1a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Pantalon large taille haute, tombé impeccable, coupe fluide.",
        description_en="High-waisted wide-leg trousers with impeccable drape.",
        composition_fr="65% viscose · 35% laine",
        composition_en="65% viscose · 35% wool",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["olive"], COLORS["camel"]], "materials": []},
        rating=4.7, reviews_count=19, reviews=_reviews(2),
        badges=[], stock=16,
    ),
    _p(
        name_fr="Trench Signature",
        name_en="Signature Trench",
        slug="signature-trench",
        category="women",
        subcategory="Manteaux",
        price=420.00,
        compare_at=490.00,
        images=[
            "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1548624313-0396c75e4b1a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Trench-coat oversize doublé, ceinture à nouer, patte d'épaule et empiècements classiques.",
        description_en="Oversize lined trench-coat with self-tie belt and classic detailing.",
        composition_fr="55% coton · 45% polyester",
        composition_en="55% cotton · 45% polyester",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["beige"], COLORS["black"]], "materials": []},
        rating=4.8, reviews_count=33, reviews=_reviews(3),
        badges=["bestseller"], stock=7,
    ),
    _p(
        name_fr="Jupe Plissée Métallisée",
        name_en="Pleated Metallic Skirt",
        slug="pleated-metallic-skirt",
        category="women",
        subcategory="Jupes",
        price=165.00,
        images=[
            "https://images.unsplash.com/photo-1583496661160-fb5886a13d44?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1548624313-0396c75e4b1a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Jupe midi plissée à reflets subtils, taille élastiquée.",
        description_en="Pleated midi skirt with subtle sheen and elastic waistband.",
        composition_fr="100% polyester recyclé",
        composition_en="100% recycled polyester",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["gold"], COLORS["silver"], COLORS["black"]], "materials": []},
        rating=4.5, reviews_count=15, reviews=_reviews(2),
        badges=["new"], stock=12,
    ),

    # ============ MEN (7) ============
    _p(
        name_fr="Manteau Camel Longueur Genou",
        name_en="Camel Knee-Length Coat",
        slug="camel-knee-length-coat",
        category="men",
        subcategory="Manteaux",
        price=480.00,
        images=[
            "https://images.unsplash.com/photo-1619603364937-8d7af41ef206?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1611095006346-d5e3313245e1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Manteau en laine vierge, coupe droite, longueur genou, poches passepoilées.",
        description_en="Virgin wool coat with straight cut, knee length, and welt pockets.",
        composition_fr="80% laine vierge · 20% cachemire",
        composition_en="80% virgin wool · 20% cashmere",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["camel"], COLORS["charcoal"], COLORS["navy"]], "materials": []},
        rating=4.9, reviews_count=44, reviews=_reviews(3),
        badges=["bestseller"], stock=9,
    ),
    _p(
        name_fr="Costume Noir Deux Pièces",
        name_en="Black Two-Piece Suit",
        slug="black-two-piece-suit",
        category="men",
        subcategory="Costumes",
        price=580.00,
        images=[
            "https://images.unsplash.com/photo-1611095006346-d5e3313245e1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Costume slim en laine super 120s, veste deux boutons et pantalon droit.",
        description_en="Slim suit in Super 120s wool with two-button jacket and straight-leg trousers.",
        composition_fr="100% laine Super 120s",
        composition_en="100% Super 120s wool",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["navy"], COLORS["charcoal"]], "materials": []},
        rating=4.8, reviews_count=27, reviews=_reviews(2),
        badges=[], stock=11,
    ),
    _p(
        name_fr="Chemise Lin Sable",
        name_en="Sand Linen Shirt",
        slug="sand-linen-shirt",
        category="men",
        subcategory="Chemises",
        price=115.00,
        images=[
            "https://images.unsplash.com/photo-1602810318660-d2c46b750f88?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1603252109303-2751441dd157?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Chemise en lin lavé, coupe régulière, col italien.",
        description_en="Washed linen shirt with regular fit and Italian collar.",
        composition_fr="100% lin lavé",
        composition_en="100% washed linen",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["sand"], COLORS["ivory"], COLORS["olive"]], "materials": []},
        rating=4.6, reviews_count=21, reviews=_reviews(2),
        badges=["new"], stock=25,
    ),
    _p(
        name_fr="Pull Col Roulé Mérinos",
        name_en="Merino Turtleneck",
        slug="merino-turtleneck",
        category="men",
        subcategory="Mailles",
        price=155.00,
        images=[
            "https://images.unsplash.com/photo-1608234807905-4466023792f5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Col roulé fin en pure laine mérinos extra-fine.",
        description_en="Thin turtleneck in extra-fine pure merino wool.",
        composition_fr="100% laine mérinos",
        composition_en="100% merino wool",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["black"], COLORS["ivory"], COLORS["olive"], COLORS["navy"]], "materials": []},
        rating=4.8, reviews_count=38, reviews=_reviews(3),
        badges=["bestseller"], stock=20,
    ),
    _p(
        name_fr="Pantalon Chino Anthracite",
        name_en="Charcoal Chino Trousers",
        slug="charcoal-chino-trousers",
        category="men",
        subcategory="Pantalons",
        price=135.00,
        images=[
            "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1624378515195-6bbdb73dff1d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Chino coupe slim en coton stretch, taille mi-haute.",
        description_en="Slim chino in stretch cotton with mid-high waist.",
        composition_fr="98% coton · 2% élasthanne",
        composition_en="98% cotton · 2% elastane",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["charcoal"], COLORS["sand"], COLORS["olive"]], "materials": []},
        rating=4.5, reviews_count=17, reviews=_reviews(2),
        badges=[], stock=28,
    ),
    _p(
        name_fr="Trench Modernisé",
        name_en="Modernised Trench",
        slug="modernised-trench",
        category="men",
        subcategory="Manteaux",
        price=395.00,
        images=[
            "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Trench déperlant, coupe oversize, ceinture nouée.",
        description_en="Water-repellent oversize trench with tie belt.",
        composition_fr="52% coton · 48% polyester",
        composition_en="52% cotton · 48% polyester",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["beige"], COLORS["black"]], "materials": []},
        rating=4.7, reviews_count=23, reviews=_reviews(2),
        badges=[], stock=8,
    ),
    _p(
        name_fr="T-Shirt Coton Épais",
        name_en="Heavyweight Cotton Tee",
        slug="heavyweight-cotton-tee",
        category="men",
        subcategory="T-Shirts",
        price=55.00,
        images=[
            "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1618354691551-c6d20f3f4c58?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="T-shirt en coton biologique 240g/m², coupe régulière.",
        description_en="Organic cotton T-shirt 240gsm with regular fit.",
        composition_fr="100% coton biologique",
        composition_en="100% organic cotton",
        variants={"sizes": SIZES_APPAREL, "colors": [COLORS["white"], COLORS["black"], COLORS["sand"], COLORS["navy"]], "materials": []},
        rating=4.6, reviews_count=42, reviews=_reviews(2),
        badges=[], stock=40,
    ),

    # ============ KIDS (5) ============
    _p(
        name_fr="Robe Enfant Lin Ivoire",
        name_en="Kids Ivory Linen Dress",
        slug="kids-ivory-linen-dress",
        category="kids",
        subcategory="Robes",
        price=85.00,
        images=[
            "https://images.unsplash.com/photo-1724365309223-89899d9e9845?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Robe en lin doux, encolure ronde, coupe évasée pour un confort optimal.",
        description_en="Soft linen dress with round neck and flared cut for maximum comfort.",
        composition_fr="100% lin lavé",
        composition_en="100% washed linen",
        variants={"sizes": SIZES_KIDS, "colors": [COLORS["ivory"], COLORS["rose"]], "materials": []},
        rating=4.9, reviews_count=18, reviews=_reviews(2),
        badges=["new"], stock=15,
    ),
    _p(
        name_fr="Ensemble Garçon Élégant",
        name_en="Boy Elegant Set",
        slug="boy-elegant-set",
        category="kids",
        subcategory="Ensembles",
        price=98.00,
        images=[
            "https://images.unsplash.com/photo-1758782213532-bbb5fd89885e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Ensemble chemise + pantalon en coton doux, parfait pour les grandes occasions.",
        description_en="Cotton shirt + trouser set — perfect for special occasions.",
        composition_fr="100% coton peigné",
        composition_en="100% combed cotton",
        variants={"sizes": SIZES_KIDS, "colors": [COLORS["ivory"], COLORS["navy"], COLORS["sand"]], "materials": []},
        rating=4.7, reviews_count=12, reviews=_reviews(2),
        badges=["bestseller"], stock=10,
    ),
    _p(
        name_fr="Pull Enfant Mailles Douces",
        name_en="Kids Soft Knit Sweater",
        slug="kids-soft-knit-sweater",
        category="kids",
        subcategory="Mailles",
        price=68.00,
        images=[
            "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1519689680058-324335c77eba?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Pull en maille douce et confortable, idéal pour la mi-saison.",
        description_en="Soft comfortable knit sweater, ideal for mid-season.",
        composition_fr="80% coton · 20% laine",
        composition_en="80% cotton · 20% wool",
        variants={"sizes": SIZES_KIDS, "colors": [COLORS["sand"], COLORS["rose"], COLORS["olive"]], "materials": []},
        rating=4.6, reviews_count=9, reviews=_reviews(1),
        badges=[], stock=20,
    ),
    _p(
        name_fr="Jean Enfant Confort",
        name_en="Kids Comfort Jeans",
        slug="kids-comfort-jeans",
        category="kids",
        subcategory="Pantalons",
        price=55.00,
        images=[
            "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1519689680058-324335c77eba?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Jean coupe droite, taille élastiquée, denim doux et flexible.",
        description_en="Straight-leg jeans with elastic waistband and soft flexible denim.",
        composition_fr="98% coton · 2% élasthanne",
        composition_en="98% cotton · 2% elastane",
        variants={"sizes": SIZES_KIDS, "colors": [COLORS["navy"], COLORS["charcoal"]], "materials": []},
        rating=4.5, reviews_count=14, reviews=_reviews(2),
        badges=[], stock=22,
    ),
    _p(
        name_fr="Manteau Enfant Camel",
        name_en="Kids Camel Coat",
        slug="kids-camel-coat",
        category="kids",
        subcategory="Manteaux",
        price=145.00,
        compare_at=175.00,
        images=[
            "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
            "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        ],
        description_fr="Manteau en laine mélangée, coupe droite, doublure douce.",
        description_en="Wool-blend coat with straight cut and soft lining.",
        composition_fr="60% laine · 40% polyester",
        composition_en="60% wool · 40% polyester",
        variants={"sizes": SIZES_KIDS, "colors": [COLORS["camel"], COLORS["charcoal"]], "materials": []},
        rating=4.8, reviews_count=11, reviews=_reviews(2),
        badges=["bestseller"], stock=6,
    ),
]
